SELECT /* SQL-ID : KRDA109BM */
       A.BASE_DATE  
     , A.EXPO_ID
	 , '2' AS  ASSET_CNCT_TPCD
	 , A.PROD_TPCD
	 , A.PROD_TPNM
	 , A.KICS_PROD_TPCD
	 , A.KICS_PROD_TPNM
	 , A.ISIN_CD
	 , A.ISIN_NM
     , NULL AS GRP_CD
     , NULL AS GRP_NM
	 , NULL AS CNPT_ID
	 , NULL AS CNPT_NM
	 , NULL AS CORP_NO
	 , NULL AS CRGR_KICS
	 , NULL AS CRGR_KICS_GRP
	 , A.FAIR_BS_AMT
	 , GREATEST(NVL(COLL_SET_AMT,0), FAIR_BS_AMT)AS GRP_EXPO_AMT
	 , B.VALUE_KICS AS TOT_ASSET_AMT
	 , C.LMT_RTO
	 , B.VALUE_KICS * C.LMT_RTO AS LMT_AMT	 
	 , GREATEST(A.FAIR_BS_AMT- (B.VALUE_KICS * C.LMT_RTO),0) AS LMT_OVER_AMT
	 , C.RISK_COEF
	 , CASE WHEN GREATEST(A.FAIR_BS_AMT - (B.VALUE_KICS * C.LMT_RTO),0) > 0 THEN GREATEST(A.FAIR_BS_AMT- (B.VALUE_KICS * C.LMT_RTO),0) * C.RISK_COEF
	        ELSE 0 END AS SCR
	 , CASE WHEN GREATEST(A.FAIR_BS_AMT - (B.VALUE_KICS * C.LMT_RTO),0) > 0 THEN A.FAIR_BS_AMT - (A.FAIR_BS_AMT * C.RISK_COEF)
	        ELSE A.FAIR_BS_AMT 
			END AS SCAF_FAIR_BS_AMT
	 , 'KRDA109BM' AS LAST_MODIFIED_BY
	 , SYSDATE AS LAST_UPDATE_DATE
	 , 'N'  AS ACCR_YN
	 , '00' AS GUNT_KEY
	 , NULL AS CNCT_ACCO_TPCD
  FROM Q_IC_EXPO A
  	 , (
--	   SELECT SUM(DECODE(RPT_COA_ID,'A',VALUE_KICS,-1*VALUE_KICS)) AS VALUE_KICS 
--	     FROM Q_IC_RPT_FVBS 
--		WHERE BASE_DATE = '$$STD_Y4MD'
--		  AND RPT_COA_ID IN ('A' , 'A3')  --총자산금액  		  
	     SELECT SUM(FAIR_BS_AMT) AS VALUE_KICS 
           FROM Q_IC_IRATE_RSLT 
          WHERE 1=1
		    AND BASE_DATE = '$$STD_Y4MD'
            AND SUBSTR(ACCO_CD, 1, 1) = '1'
            AND NVL(ACCO_CLCD, '9') NOT IN ('4','5') 
            AND IRATE_RPT_TPCD IN ('1', '2')
	   ) B
	 , (SELECT * 
	      FROM IKRUSH_SHCK_CNCT 
		 WHERE '$$STD_Y4MD' BETWEEN APLY_STRT_DATE AND APLY_END_DATE
		   AND CNCT_RISK_DTLS_TPCD IN ('C2')
	   ) C 
 WHERE A.BASE_DATE = '$$STD_Y4MD'
--   AND A.ASSET_TPCD = 'PRPT'
-- AND (KICS_PROD_TPCD IN ('340','341','346','347') OR ASSET_TPCD = 'PRPT')  	-- 부동산 및 부동산PF
 AND (KICS_PROD_TPCD IN ('340','341','346','347','350','351','352','353') OR ASSET_TPCD = 'PRPT')  --20240523:  부동산담보대출 & 부동산PF 및 보유부동산