WITH /* SQL-ID : KRDA113BM */ T_AAA AS
(
   SELECT BASE_DATE
        , IRATE_RPT_COA
        , IRATE_RPT_TPCD
        , SUM(DECODE(SUBSTR(IRATE_RPT_COA, 1, 2), '2N', -IR_EXPO_SCEN01, IR_EXPO_SCEN01))       AS IR_EXPO_SCEN01        -- Q_IC_IRATE_RSLT에서 부채계정의 금액은 양수로 전환한 상태임(Q_IC_PRE_EXPO에서 처리함)
        , SUM(DECODE(SUBSTR(IRATE_RPT_COA, 1, 2), '2N', -IR_EXPO_SCEN02, IR_EXPO_SCEN02))       AS IR_EXPO_SCEN02        -- Q_IC_IRATE_SMR에서는 합계의 편의를 위해 부채계정의 금액을 다시 음수로 전환함
        , SUM(DECODE(SUBSTR(IRATE_RPT_COA, 1, 2), '2N', -IR_EXPO_SCEN03, IR_EXPO_SCEN03))       AS IR_EXPO_SCEN03        -- 금리리스크 화면 쿼리에서는 필요에 따라(e.g.화면2번) 다시 부채계정값을 양수로 전환하기도 하였음
        , SUM(DECODE(SUBSTR(IRATE_RPT_COA, 1, 2), '2N', -IR_EXPO_SCEN04, IR_EXPO_SCEN04))       AS IR_EXPO_SCEN04
        , SUM(DECODE(SUBSTR(IRATE_RPT_COA, 1, 2), '2N', -IR_EXPO_SCEN05, IR_EXPO_SCEN05))       AS IR_EXPO_SCEN05
        , SUM(DECODE(SUBSTR(IRATE_RPT_COA, 1, 2), '2N', -IR_EXPO_SCEN06, IR_EXPO_SCEN06))       AS IR_EXPO_SCEN06
        , SUM(DECODE(SUBSTR(IRATE_RPT_COA, 1, 2), '2N', -IR_EXPO_SCEN07, IR_EXPO_SCEN07))       AS IR_EXPO_SCEN07
        , SUM(DECODE(SUBSTR(IRATE_RPT_COA, 1, 2), '2N', -IR_EXPO_SCEN08, IR_EXPO_SCEN08))       AS IR_EXPO_SCEN08
        , SUM(DECODE(SUBSTR(IRATE_RPT_COA, 1, 2), '2N', -IR_EXPO_SCEN09, IR_EXPO_SCEN09))       AS IR_EXPO_SCEN09
        , SUM(DECODE(SUBSTR(IRATE_RPT_COA, 1, 2), '2N', -IR_EXPO_SCEN10, IR_EXPO_SCEN10))       AS IR_EXPO_SCEN10
        , SUM(DECODE(SUBSTR(IRATE_RPT_COA, 1, 2), '2N', -IR_EXPO_SCEN11, IR_EXPO_SCEN11))       AS IR_EXPO_SCEN11
        , SUM(DECODE(SUBSTR(IRATE_RPT_COA, 1, 2), '2N', -IR_EXPO_SCEN12, IR_EXPO_SCEN12))       AS IR_EXPO_SCEN12
        , SUM(DECODE(SUBSTR(IRATE_RPT_COA, 1, 2), '2N', -IR_EXPO_SCEN13, IR_EXPO_SCEN13))       AS IR_EXPO_SCEN13
        , SUM(DECODE(SUBSTR(IRATE_RPT_COA, 1, 2), '2N', -IR_EXPO_SCEN14, IR_EXPO_SCEN14))       AS IR_EXPO_SCEN14
        , 'KRDA113BM'                                                                          AS LAST_MODIFIED_BY
        , SYSDATE                                                                              AS LAST_UPDATE_DATE
     FROM Q_IC_IRATE_RSLT
    WHERE 1=1
      AND BASE_DATE = '$$STD_Y4MD'
--      AND ACCO_CLCD NOT IN ('4')  -- 2024.05.09 대상모두가져오도록  주석처리
    GROUP BY
          BASE_DATE
        , IRATE_RPT_COA
        , IRATE_RPT_TPCD
)
SELECT * FROM T_AAA